### ISSUE TITLE
Advanced Group

### ISSUE THREAD

**Issue by Sohan9764** [latracal/grigora-kit#32]
1) If Advanced Group with normal color style is added inside Advanced Group with Gradient style then inner Advanced Group replicates Gradient style of parent Advanced Group.
2) If Box Shadow on hover with color is applied to Advanced Group then on hover normal color of Box Shadow flashes and fades out.
3) In Advanced Group transform on hover scale does not have 0.04 pointer value but it is added in normal transform scale

**Comment by latracal** [comment]
Fixed in https://github.com/latracal/grigora-kit/commit/4fe85adfbdf72edbcefee5e0e06325cc1554b532
